#ifndef __HW_CONFIG_H
#define __HW_CONFIG_H
#include "csr.h"

/* /!\ keep in sync with csr.h  /!\ */

/* pci */
#define PCIE_FPGA_VENDOR_ID 0x10ee
#define PCIE_FPGA_DEVICE_ID 0x7022

/* dma */
#define DMA_IRQ_DISABLE (1<<16)
#define DMA_LAST_DISABLE (1<<17)

#define DMA_CHANNEL_COUNT 1
#define DMA_BUFFER_PER_IRQ 32
#define DMA_BUFFER_COUNT 256
#define DMA_BUFFER_SIZE 16384
//#define DMA_BUFFER_ALIGNED


/* pcie dma */
#define PCIE_DMA_WRITER_ENABLE_OFFSET 0x0000
#define PCIE_DMA_WRITER_TABLE_VALUE_OFFSET 0x0004
#define PCIE_DMA_WRITER_TABLE_WE_OFFSET 0x000c
#define PCIE_DMA_WRITER_TABLE_LOOP_PROG_N_OFFSET 0x0010
#define PCIE_DMA_WRITER_TABLE_LOOP_STATUS_OFFSET 0x0014
#define PCIE_DMA_WRITER_TABLE_LEVEL_OFFSET 0x0018
#define PCIE_DMA_WRITER_TABLE_FLUSH_OFFSET 0x001c
#define PCIE_DMA_READER_ENABLE_OFFSET 0x0020
#define PCIE_DMA_READER_TABLE_VALUE_OFFSET 0x0024
#define PCIE_DMA_READER_TABLE_WE_OFFSET 0x002c
#define PCIE_DMA_READER_TABLE_LOOP_PROG_N_OFFSET 0x0030
#define PCIE_DMA_READER_TABLE_LOOP_STATUS_OFFSET 0x0034
#define PCIE_DMA_READER_TABLE_LEVEL_OFFSET 0x0038
#define PCIE_DMA_READER_TABLE_FLUSH_OFFSET 0x003c
#define PCIE_DMA_LOOPBACK_ENABLE_OFFSET 0x0040

#endif /* __HW_CONFIG_H */
